[JOSS] Reproducibility - Resolve issue with looking for benchmark tests in the wrong path. (#7)
* Resolve issue with looking for benchmark tests in the wrong path.

In #5, benchmarks were moved to the tests/ directory from the benchmark_code/ directory. This change updates that path.

This error is received on attempting to run the benchmarks:

```sh
$ python benchmarks/run_benchmarks.py --verbose
===========================================
    Ackermann
===========================================
Traceback (most recent call last):
  File "/home/aholmes/repos/pyccel-benchmarks/benchmarks/run_benchmarks.py", line 209, in <module>
    shutil.copyfile(test_file, os.path.join(new_folder, basename))
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/aholmes/repos/pyccel-benchmarks/benchmarks/benchmark_code/ackermann_mod.py'
```

Related: openjournals/joss-reviews#4991

* Benchmark of pyccel/pyccel@85993300d5a59396dbacd51f7f51d4bdf788bad0

* Update performance comparison

* Update README and version

Co-authored-by: Pyccel/pyccel <41898282+github-actions[bot]@users.noreply.github.com>